[package]
name = "rsync-fetcher"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
aws-config = "0.54"
aws-sdk-s3 = "0.24"
bincode = "2.0.0-rc.2"
blake2 = "0.10"
clap = { version = "4.1", features = ["derive"] }
clean-path = "0.2"
color-eyre = "0.6"
digest = "0.10"
either = "1.8"
eyre = "0.6"
futures = "0.3"
indicatif = "0.17"
md4 = "0.10"
num = "0.4"
pin-project = "1.0"
rand = "0.8"
redis = { git = "https://github.com/PhotonQuantum/redis-rs", features = ["aio", "tokio-comp"] }
scan_fmt = "0.2"
tempfile = "3.3"
tokio = { version = "1.25", features = ["full"] }
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
unix_mode = "0.1"
url = "2.3"
