[package]
name = "rsync-gateway"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3"
aws-config = "0.54"
aws-sdk-s3 = "0.24"
bincode = "2.0.0-rc.2"
clap = { version = "4.1", features = ["derive"] }
redis = { git = "https://github.com/PhotonQuantum/redis-rs", features = ["aio", "tokio-comp"] }
