bind = ["127.0.0.1:8080", "[::1]:8080"]
s3_url = ""
s3_region = ""
update_interval = 300
database_url = ""

[endpoints.fedora]
s3_bucket = "rsync"
s3_prefix = "fedora"
namespace = "fedora"

[endpoints.debian]
s3_bucket = "rsync"
s3_website = "debian"
namespace = "debian"